t42_backend:
    resource: "@T42BackendBundle/Controller/"
    type:     annotation
    prefix:   /

T42TestimoniosBundle:
    resource: "@T42TestimoniosBundle/Controller/"
    type:     annotation    
