t42_backend:
    resource: "@T42BackendBundle/Controller/"
    type:     annotation

t42_testimonios:
    resource: "@T42TestimoniosBundle/Controller/"

t42_destinos:
    resource: "@DestinosBundle/Controller/"
    type:     annotation