t42_imagen:
    resource: "@T42ImagenBundle/Controller/"
    type:     annotation
    prefix:   /

t42_backend:
    resource: "@T42BackendBundle/Controller/"
    type:     annotation

t42_testimonios:
    resource: "@T42TestimoniosBundle/Controller/"

t42_destinos:
    resource: "@T42DestinosBundle/Controller/"
    type:     annotation

t42_contacto:
    resource: "@T42ContactoBundle/Controller/"
    type:     annotation

t42_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

t42_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

t42_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

t42_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /admin/resetting

t42_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /admin/profile  

t42_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group    

t42_user_invitation:
    resource: "@T42UserBundle/Controller/"
    type:     annotation