security:
  
    firewalls:      
        admin_area:
            pattern:  ^/admin
            http_basic: 
              realm: "Area Segura"
            logout: true

    access_control:
        - { path: ^/admin, roles: 'ROLE_ADMIN' }
    
    providers:
        in_memory:
            memory:
                users:
                    usuario:  { password: usuario, roles: 'ROLE_USER' }                    
                    admin:    { password: usuario, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
